Sage-Bionetworks/service-catalog-library

- ec2/sc-ec2-linux-ra.yaml
- ec2/sc-ec2-windows-ra.yaml
Adding default vpc to test travis.
> Add default vpc for linux and windows

- ec2/sc-ec2-linux-ra.yaml
re-add using a condition to choose public or private subnet
> Use condition to choose subnet

- ec2/sc-ec2-linux-ra.yaml
> Remove unnecessary VPC parameter

- ec2/sc-ec2-linux-ra.yaml
Allows a choice of linux distribution to user.
> Linux distro

- ec2/sc-product-ec2-linux.yaml
- ec2/sc-product-ec2-windows.yaml
- vpc/sc-product-vpc.yaml
change support text for currently visible products
> Change support text for published products

- vpc/sc-vpc-ra.yaml
Add VPCName parameter, use it for the VPC Name tag and for exports
> Give the vpc a friendly name

- vpc/sc-vpc-ra.yaml
forgot to add vpc name to the interface. Whoops.
> Add the new VPCName parameter to the interface

- ec2/sc-ec2-linux-ra.yaml
- ec2/sc-ec2-windows-ra.yaml
Update ImportValue in ec2 products to use ScipoolInternalVPC
> Fix ImportValue in EC2 product templates

- s3/sc-portfolio-s3-basic.yaml
- templates/taskcat-verify-all.yaml
Add a portfolio that only contains S3 products for the basic use case
> Basic portfolio of S3 products

- s3/sc-s3-encrypted-ra.yaml
replace policy in encrypted bucket template with one in synapse bucket template
> Make encrypted bucket policy same as synapse bucket policy

- ec2/sc-ec2-linux-jumpcloud.yaml
- ec2/sc-portfolio-ec2.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
Update Ingress/Egress CidrIp, and resource name in scripts, for ec2 jumpcloud template
Making these changes allowed the creation of an instance that correctly inits and could be connected to with a jumpcloud ID.
Also added jumpcloud product to EC2 portfolio.
> Fix CIDR and resource names

- ec2/sc-ec2-linux-ra.yaml
Update sc-ec2-linux-ra with changes made to sc-ec2-linux-jumpcloud in PR #33 as applicable
> Apply sc-ec2-linux-jumpcloud changes to sc-ec2-linux-ra

- ec2/sc-ec2-linux-jumpcloud.yaml
- Add param VolumeSize
- Add EBS volume
- Volume always encrypted <- should we make this optional?
> Add EBS volume to linux jumpcloud template

- ec2/sc-ec2-linux-ra.yaml
- ec2/sc-ec2-windows-ra.yaml
apply same volume treatment as for sc-ec2-linux-jumpcloud
> Add volumes to sc-ec2-linux-ra and sc-ec2-windows-ra

- ec2/sc-ec2-windows-jumpcloud.yaml
apply volume pattern to windows jumpcloud template
> Add volume to windows jumpcloud template

- ec2/sc-portfolio-ec2.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
Added a windows jumpcloud product, added it to ec2 portfolio, removed the products without jumpcloud from the portfolio
> Change Ec2 portfolio to jumpcloud only

- iam/sc-enduser-iam.yaml
- iam/sc-s3-launchrole.yaml
1. add createchangest to s3 role
2. remove deny on GetTemplateSummary to see if that's what's blocking S3Object macro
> Add createchangset s3 role

- ec2/sc-ec2-windows-jumpcloud.yaml
> Add OwnerEmail and change some text in sc-ec2-windows-jumpcloud

- iam/sc-enduser-iam.yaml
This reverts commit 9b2e4f3334b312c720e0fabe17c7754e48f026dd.
Revert this to debug permissions issue with S3 synapse bucket
provisiong using the SC
> Revert "Add manage policy to hide template to protect secrets"

- ec2/sc-ec2-linux-jumpcloud.yaml
Add init step to collect env vars into file for use in other init steps and convert associate_jc_systems into file
> Env vars file and associate_jc_systems file

- ec2/sc-ec2-linux-jumpcloud.yaml
- Remove too-permissive ssm policies from InstanceRole
- Remove all patching resources. Patching will be re-added when IT can come up with a strategy for this -- it is outside the scope of Service Catalog development.
- Update ubuntu AMI.
> Remove too permissive SSM policies

- iam/sc-enduser-iam.yaml
Fixes https://sagebionetworks.jira.com/browse/SC-8
> Add policy to expand permitted actions for Service Catalog users

- iam/sc-enduser-iam.yaml
allow RoleAndGroupName parameter
revise exports
> Allow the name of the Group and Role for end users to be configured

- ec2/sc-portfolio-ec2-development.yaml
- ec2/sc-portfolio-ec2.yaml
New portfolio for EC2 development
Allows configuration of group and role
> Create development portfolio for EC2 with configurable group and role

- s3/sc-portfolio-s3-basic-development.yaml
- s3/sc-portfolio-s3-basic.yaml
Apply configurable prinicipals pattern to S3 portfolio and add development portfolio for S3 too
This PR is contingent on the final pattern settled on in PR #53
> Sc-6/configurable-principal-s3

- ci/taskcat-params-verify-all.json
- templates/taskcat-verify-all.yaml
Update taskcat for EC2 and S3 portfolio template changes
> Update taskcat for EC2 and S3 portfolio template changes

- s3/sc-portfolio-s3-basic.yaml
products mixed up in s3-basic portfolio
> Remove synapse product and add encrypted bucket product

- iam/sc-enduser-iam.yaml
This reverts commit 337326bfcbd0acb077733c43064a6f6ce8f28218.
This is change is not neccessary, PR #57 fixes SC s3 synapse bucket
> Revert "attempt to fix SC s3 synapse bucket product (#49)"

- iam/sc-enduser-iam.yaml
This reverts commit a9fe775dda2f6ff4a01b73222d1c60822e774aa9.
We have completed debugging permissions issue with S3 synapse bucket
provisiong.  The cloudformation:GetTemplateSummary deny wasn't the
problem.
> Revert "Revert "Add manage policy to hide template to protect secrets" (#45)"

- s3/sc-product-s3-private-enc.yaml
- s3/sc-product-s3-synapse.yaml
> Text edits to bring S3 product names in line with EC2 style

- iam/sc-enduser-iam.yaml
This reverts commit 4adf950d7d68ce3652713a2e00a47bd03a3d1324.
We gave up on SC service actions therefore we don't need this
anymore.
> Revert "[SC-26] update SC end user permissions"

- ec2/sc-portfolio-ec2-development.yaml
- ec2/sc-portfolio-ec2.yaml
> Move windows product out of development portfolio

- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
- ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml
* Add a tag to allow users in park my cloud to start and
stop their instances.
* Update tags to help identify instances in the AWS console
> [SC-37] add PMC tag

- ec2/sc-ec2-linux-jumpcloud-development.yaml
- ec2/sc-ec2-windows-jumpcloud-development.yaml
- ec2/sc-portfolio-ec2-development.yaml
- ec2/sc-product-ec2-linux-jumpcloud-development.yaml
- ec2/sc-product-ec2-windows-jumpcloud-development.yaml
- s3/sc-portfolio-s3-basic-development.yaml
- s3/sc-product-s3-private-enc-development.yaml
- s3/sc-product-s3-synapse-development.yaml
- s3/sc-s3-encrypted-ra-development.yaml
- s3/sc-s3-synapse-ra-development.yaml
Creates permanent development versions of products for all existing products. This allows faster development as the developer does not have to set up new products and edit the development portfolio over and over -- they only have to copy the latest version of the existing production product to the development version.
JIRA issue: https://sagebionetworks.jira.com/browse/SC-62
> Create development-version products and templates for all existing products

- ec2/sc-ec2-windows-jumpcloud-development.yaml
- ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml
refer to script source in github repo for env vars and name tag
> Use infra-utils scripts moved to infra-utils for env vars and name tagging

- ec2/sc-product-ec2-linux-jumpcloud-development.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
- ec2/sc-product-ec2-windows-jumpcloud-development.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
Remove some inaccurate language from EC2 product descriptions.
> Correct EC2 product descriptions

- iam/sc-enduser-iam.yaml
Apply trust policy to the synapse OIDC identity provider.
This PR depends on PR https://github.com/Sage-Bionetworks/scipoolprod-infra/pull/72
> [SC-64] Update policy for Synapse OIDC IDP

- dev-deploy-templates.sh
- ec2/sc-ec2-linux-jumpcloud-workflows-development.yaml
- ec2/sc-portfolio-ec2-development.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows-development.yaml
This adds the development version of the Workflow product.
> Add development workflows product

- ec2/sc-ec2-linux-jumpcloud-workflows-development.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
- ec2/sc-portfolio-ec2.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows-development.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
This is the production version of the workflows product. The substantial changes were already approved for the development version in PR #93 .
> Add production workflows product

- ec2/sc-ec2-linux-jumpcloud-development.yaml
- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
Only port that's allowed open when putting instance into the public
subnet is the SSH port.
> [SC-70] remove OpenPorts parameter

- ec2/development/sc-portfolio-ec2-development.yaml
- ec2/development/sc-product-ec2-linux-jumpcloud-development.yaml
- ec2/development/sc-product-ec2-linux-jumpcloud-notebook-development.yaml
- ec2/development/sc-product-ec2-linux-jumpcloud-workflows-development.yaml
- ec2/development/sc-product-ec2-windows-jumpcloud-development.yaml
- ec2/development/tthyer/sc-portfolio-ec2-development-tthyer.yaml
- ec2/development/tthyer/sc-product-ec2-linux-jumpcloud-development-tthyer.yaml
- s3/development/sc-portfolio-s3-basic-development.yaml
- s3/development/sc-product-s3-private-enc-development.yaml
- s3/development/sc-product-s3-synapse-development.yaml
This fixes paths in dev portfolios and products.
> Fix paths in development templates

- ec2/development/sc-ec2-linux-jumpcloud-development.yaml
- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
Need to update to latest Ubuntu AMI and fix UserData script. For the latter, using same fix that was made for Workflows template.
> Sc 75/fix ubuntu userdata

- ec2/development/sc-ec2-linux-jumpcloud-development.yaml
- ec2/development/sc-ec2-linux-jumpcloud-notebook-development.yaml
- ec2/development/sc-ec2-linux-jumpcloud-workflows-development.yaml
- ec2/development/tthyer/sc-ec2-linux-jumpcloud-development-tthyer.yaml
- ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
Use scripts moved to service-catalog-utils
> Externalize scripts 

- ec2/development/sc-ec2-linux-jumpcloud-workflows-development.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
Update workflows image to v1.0.1
> Update workflows image to v1.0.1

- ec2/development/sc-ec2-linux-jumpcloud-notebook-development.yaml
- ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
Updating notebook image to v1.0.1
> Updating notebook image to v1.0.1

- ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
Remove items that are added to the base-ubuntu-bionic AMI:
Remove cnf helper script install:
* https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/pull/20
Remove install jq:
* https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/pull/21
* https://github.com/Sage-Bionetworks-IT/packer-base-amazonlinux2/pull/6
> [IT-852] refactor ec2 linux templates

- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
Associate existing EC2 SC actions with SC EC2 products.  The
actions allow a user to stop, start and restart instances.
This PR depends on having already installed the stop, start and
restart SC actions.  The SC actions are installed with
PR https://github.com/Sage-Bionetworks/scipoolprod-infra/pull/92
> [SC-26] Associate SC actions with products

- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
Fix the reference to SC EC2 actions.  The names are defined by
stack 'sc-ec2-actions' from PR https://github.com/Sage-Bionetworks/scipoolprod-infra/pull/92
> Fix reference

- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
This reverts commit e43047e952622bc6da99e4b305f4b1e433bc16c2.
> Revert "[SC-26] Associate SC actions with products (#108)"

- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
- iam/sc-enduser-iam.yaml
Reverts Sage-Bionetworks/scipoolprod-sc-lib-infra#111
> Revert "Add StartSession policy for remote access"

- s3/development/sc-s3-encrypted-ra-development.yaml
- s3/development/sc-s3-synapse-ra-development.yaml
- s3/sc-s3-encrypted-ra-v1.0.0.yaml
- s3/sc-s3-synapse-ra-v1.0.0.yaml
This adds the custom resource which tags S3 buckets to all the S3 templates in the library.
Depends on:
- https://github.com/Sage-Bionetworks-IT/cfn-cr-bucket-tagger/pull/1
- https://github.com/Sage-Bionetworks/scipoolprod-infra/pull/93
> Add S3BucketTagger to s3 bucket templates

- s3/development/sc-s3-encrypted-ra-development.yaml
- s3/development/sc-s3-synapse-ra-development.yaml
- s3/sc-s3-encrypted-ra-v1.0.0.yaml
- s3/sc-s3-synapse-ra-v1.0.0.yaml
Reverts Sage-Bionetworks/scipoolprod-sc-lib-infra#110
> Revert "Add S3BucketTagger to s3 bucket templates"

- s3/development/sc-s3-encrypted-ra-development.yaml
- s3/development/sc-s3-synapse-ra-development.yaml
- s3/sc-s3-encrypted-ra-v1.0.0.yaml
- s3/sc-s3-synapse-ra-v1.0.0.yaml
Reverts Sage-Bionetworks/scipoolprod-sc-lib-infra#119
> Revert "Revert "Add S3BucketTagger to s3 bucket templates""

- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
- iam/sc-enduser-iam.yaml
This PR corrects the name of the ServiceCatalogEndusers role.
> Fix RoleId import value to tag instances

- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
- iam/sc-enduser-iam.yaml
Reverts Sage-Bionetworks/scipoolprod-sc-lib-infra#121
To get RoleId, I should have used GetAtt rather than Ref
> Revert "Fix RoleId import value to tag instances"

- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
- iam/sc-enduser-iam.yaml
This re-adds the changes to the repo that should get the builder working again, but does not revert changes that led to this state.
> Quick fixes to templates

- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
> Fix syntax error

- ec2/sc-portfolio-ec2.yaml
We export the portfolio ID so we can import into a downstream
template.
> [SC-128] Export the portfolio Id

- dev-deploy-templates.sh
- ec2/development/sc-ec2-linux-jumpcloud-development.yaml
- ec2/development/sc-ec2-linux-jumpcloud-notebook-development.yaml
- ec2/development/sc-ec2-linux-jumpcloud-workflows-development.yaml
- ec2/development/sc-ec2-windows-jumpcloud-development.yaml
- ec2/development/sc-portfolio-ec2-development.yaml
- ec2/development/sc-product-ec2-linux-jumpcloud-development.yaml
- ec2/development/sc-product-ec2-linux-jumpcloud-notebook-development.yaml
- ec2/development/sc-product-ec2-linux-jumpcloud-workflows-development.yaml
- ec2/development/sc-product-ec2-windows-jumpcloud-development.yaml
- ec2/development/tthyer/sc-ec2-linux-jumpcloud-development-tthyer.yaml
- ec2/development/tthyer/sc-portfolio-ec2-development-tthyer.yaml
- ec2/development/tthyer/sc-product-ec2-linux-jumpcloud-development-tthyer.yaml
- s3/development/sc-portfolio-s3-basic-development.yaml
- s3/development/sc-product-s3-private-enc-development.yaml
- s3/development/sc-product-s3-synapse-development.yaml
- s3/development/sc-s3-encrypted-ra-development.yaml
- s3/development/sc-s3-synapse-ra-development.yaml
Reverts Sage-Bionetworks/service-catalog-library#127
Keeping current development process for now as there's no good workaround for the LoadTemplateFromURL problem.
> Revert "Remove dev templates"

- iam/cfn-ssm-param-policy.yaml
Move policy from scipoolprod-infra repo to this repo so it can
be shared accross multiple deployments.
> [SC-127] share policy

- iam/sc-enduser-iam.yaml
Adding this statement allows a user to terminate their own sessions and not sessions tagged with other userids.
> Allow terminate sessions

- common/sc-tag-options.j2
Move tag options template from scipoolprod-infra repo to this
repo so it can be shared accross multiple deployments.
> [SC-127] Share tag optins template

- s3/sc-product-s3-private-enc.yaml
- s3/sc-product-s3-synapse.yaml
The portfolio depends on the product nested stacks to output
ProductId
> [SC-111] Ouput S3 product IDs

- ec2/sc-portfolio-ec2.yaml
- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
Nested stacks make things confusing and makes cloudformation
very difficult to test.  We remove nested stack and will deploy
stacks with sceptre.  Scepter will manage the dependencies between
stacks.
> [SC-111] refactor to remove nested stacks

- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
- s3/sc-product-s3-private-enc.yaml
- s3/sc-product-s3-synapse.yaml
PortfolioId is now a required parameter so that we can create testing products that we associate with testing portfolios.
> Require PortfolioId in product parameters

- ec2/sc-ec2-actions.yaml
- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
* rename cfn-sc-actions-provider to cfn-cr-sc-actions-provider due
the lambda move to https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-actions-provider
* associate the 3 EC2 actions (stop/start/restart) with each product
This PR depends on:
https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-actions-provider/pull/4
https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-actions-provider/pull/5
> [SC-26] Add SC actions to products

- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
This partially reverts commit d5a40bb174cb9a127a4d34d063bfcf7e4adc6f0e
Adding all 3 service actions at one time failed.
> partial revert of d5a40bb1

- s3/sc-s3-encrypted-ra-v1.0.0.yaml
A condition was missing on the encrypted bucket template.
> [SC-113] Add missing condition to encrypted bucket

- ec2/sc-ec2-action-associations.yaml
Use the SC actions custom resource automator.
This PR depends on PR https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-actions-provider/pull/7
> [SC-26] template to associate actions to products

- ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml
* Update windows product to use ver v1.0.6 util scripts
* Move JC stuff to the end because it depends on instance tags
> Fix windows provisioner

- ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
- ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml
We add ConnectionURI to all products for testing then we can remove it for the ones that don't make sense in a follow on PR.
> Add ConnectionURI to all products

- ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
Update for the following AMI changes:
* https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/36
* https://github.com/Sage-Bionetworks-IT/packer-workflows/pull/8
> Update to latest AMIs

- ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
Provide info on how to connect to RStudio after provisioing
the notebook product.
> [SC-150] Add a RStudio connection link

- ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
The URL needs the IP address not the instance ID
> fix NotebookConnectionURI

- ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
- ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
This 
- removes the public/private network parameter
- removes public subnet security group creation
> Remove public subnet option from linux products

- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
- ec2/sc-product-ec2-windows-jumpcloud.yaml
Parameterize ReplaceProvisioningArtifacts in SC product templates
because we want to set that to true for develop ENV and false
for prod ENV.
> [SC-171] parameterize product updates

- s3/sc-s3-synapse-ra-v1.0.1.yaml
The synapse AWS account is very unlikely to change therefore
no need to parameterize SynapseProdARN
> [SC-166] Remove SynapseProdARN

- s3/sc-product-s3-synapse.yaml
Crete new S3 product version to include
* Remove SynapseProdARN
This PR depends on PR #195
> [SC-166] Update S3 product

- s3/sc-product-s3-private-enc.yaml
- s3/sc-product-s3-synapse.yaml
- s3/sc-s3-encrypted-ra-v1.0.1.yaml
- s3/sc-s3-synapse-ra-v1.0.2.yaml
Use DependsOn to force S3 custom resources to execute serially rather than in parallel
> Fix OperationAbortError in S3BucketTagger

- ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.1.yaml
- ec2/sc-ec2-linux-jumpcloud-v1.0.1.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.1.yaml
- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-product-ec2-linux-jumpcloud.yaml
Update AMIs to pick up fix for snap relocation error
> Update AMIs for linux, notebook and workflows templates

- ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
Fullfil @tthyer's request..
Hey Khai, can you add the remaining products into the
external portfolio even if NotebookConnectionURI is not fully working
yet off VPN?
> [SC-195] add products to external portfolio

- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-ec2-linux-jumpcloud.yaml
- ec2/sc-ec2-windows-jumpcloud.yaml
Only support Connection URI, no more jumpcloud access.
> [SC-100] Remove jumpcloud access

- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-ec2-linux-jumpcloud.yaml
- ec2/sc-ec2-windows-jumpcloud.yaml
Add strides account to mapping so we can automatically set the
subnets for EC2 instances.
> [SC-209] add strides account params

- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-ec2-linux-jumpcloud.yaml
- ec2/sc-ec2-windows-jumpcloud.yaml
Include the cfn-service-catalog-snippets.yaml parmeters in mapping.
depends on Sage-Bionetworks/admincentral-infra#99
> use service catalog snippets mapping

- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
depends on Sage-Bionetworks/service-catalog-utils#16
> [SC-241] update apache script version

- .pre-commit-config.yaml
- s3/sc-s3-encrypted-ra.yaml
- s3/sc-s3-synapse-ra.yaml
Add option to restrict downloads to same region as provisioned bucket
Depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-same-region-bucket-download/pull/1
> Add option to restrict downloads to same region as provisioned bucket (SC-240)

- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
depends on https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/42 and https://github.com/Sage-Bionetworks/service-catalog-utils/pull/18
> Include SSM Parameter encrypted by CMK to pass Synapse user credentials (SC-260)

- ec2/sc-ec2-linux-docker.yaml
- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-ec2-windows-jumpcloud.yaml
- s3/sc-s3-encrypted-ra.yaml
- s3/sc-s3-synapse-ra.yaml
Provide a link to our public service catalog documentation from the
service catalog UI.
> Link to service catalog documentation

- ec2/sc-ec2-linux-docker.yaml
- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
- ec2/sc-ec2-linux-jumpcloud-workflows.yaml
- ec2/sc-ec2-linux-jumpcloud.yaml
Allow users to provision x2gd, g4dn, and i3en instance types
> [SC-360] Allow instance types x2gd, g4dn, i3en

- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
Update the AMI used for the R-Studio Notebook instance.
> SC-318 update AMI

- batch/sc-batch-fargate.yaml
* add docs
* fix reference to VPC
* fix reference to secrets
> Fix SC batch fargate product

- s3/sc-s3-encrypted-ra.yaml
- s3/sc-s3-synapse-ra.yaml
pin to a specific version of the cfn-cr-same-region-bucket-download lambda
which can be found at..
https://bootstrap-awss3cloudformationbucket-19qromfd235z9.s3.amazonaws.com/index.html#cfn-cr-same-region-bucket-download
> pin to a version of cfn-cr-same-region-bucket-download

- ec2/sc-ec2-windows-jumpcloud.yaml
update powershell scripts to provision windows instances
> [SC-402] Update infra-utils

- ec2/sc-ec2-windows-jumpcloud.yaml
Remove automated association of windows instance to jumpcloud user. This still allows us to do the JC user and instance association manually in jumpcloud.
> [SC-404] Stop JC exposure

- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
The service catalog product template creates KMS keys for notebook instances however key roation was not enable on them. This change is to enable key rotation for the KMS keys.
> [IT-2317] Enable kms key rotation

- ec2/sc-ec2-linux-jumpcloud-notebook.yaml
Update AMI and paths and service catalog scripts from the updated image.
depends on https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/68 https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-jammy/pull/6 https://github.com/Sage-Bionetworks/service-catalog-utils/pull/21
> [SC-383] update to match image update

- templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml
This PR updates the version of service-catalog-utility (to pick up fix on apache .conf rewrite).
Depends on https://github.com/Sage-Bionetworks/service-catalog-utils/pull/22 .
> SC-383: Update utility version

- templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml
This PR pulls the change from https://github.com/Sage-Bionetworks/service-catalog-utils/pull/24 into service-catalog-library.
Depends on https://github.com/Sage-Bionetworks/service-catalog-utils/pull/24 .
> SC-383: Simplified RE to configure apache

- templates/ec2/sc-ec2-linux-docker.yaml
Update AMI for docker product to pick up fix in PR https://github.com/Sage-Bionetworks-IT/packer-amazonlinux-docker/pull/6
> [IT-2871] update AMI for docker product

- templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml
This PR uses the AMI @zaro0508 built from the original v2.1.3 tag in product v1.1.45.
> SC-383: Fix AMI ID

- templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml
* pick up fix for apache reverse proxy
* pick up installation of python synapseclient
depends on https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/86 https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/85
> [SC-383] Update AMI for service catalog notebook product

- templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml
This PR updates the AMI for the JUmpcloud notebook.
Requires https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/89
> SC-383: Update AMIID

- templates/batch/sc-batch-fargate.yaml
Upgrade lambda-batch-trigger to address a dependabot finding.
> [IT-2891] Address dependabot finding

- templates/ec2/sc-ec2-linux-docker.yaml
This PR puts back @jesusaurus test AMI ID on top IT-3318's changes.
> IT-3318: Revert change AMIID

- templates/ec2/sc-ec2-linux-docker.yaml
Update the AMI with the package 'chkconfig' needed by the systemd unit created in AWS::CloudFormation::Init
Depends on Sage-Bionetworks-IT/packer-amazonlinux-docker#12
> [SC-409] Test another AMI update

- templates/ec2/sc-ec2-linux-docker.yaml
PR Checklist:
[ ] Describe and explain your intentions for this change
[ ] Setup pre-commit and run the validators (info in README.md)
To validate files run: `pre-commit run --all-files`
> [SC-409] Test updated env_vars script

- templates/ec2/sc-ec2-linux-docker-notebook.yaml
Update version of notebook-reverse-proxy to v1.0.1
> Update version of notebook-reverse-proxy to v1.0.1

- templates/s3/sc-s3-encrypted-ra.yaml
- templates/s3/sc-s3-synapse-ra.yaml
Upgrade python version used by cfn-cr-same-region-bucket-download lambda.
> [IT-3466] Upgrade python version used by lambda

- templates/ec2/sc-ec2-linux-docker.yaml
PR Checklist:
[ ] Describe and explain your intentions for this change
[ ] Setup pre-commit and run the validators (info in README.md)
To validate files run: `pre-commit run --all-files`
> [IT-3697] Test latest docker image before tagging

- templates/s3/sc-s3-encrypted-ra.yaml
- templates/s3/sc-s3-synapse-ra.yaml
Use the latest version of the lambda, updating dependencies.
> [IT-3547] Update same region download lambda

- templates/ec2/sc-ec2-linux-docker-notebook.yaml
Update base system packages used by the Docker Notebook product.
> Update Docker Notebook base AMI

- templates/batch/sc-batch-fargate.yaml
Periodic update of the batch product
> [IT-3547] Update lambda-batch-trigger version

- templates/s3/sc-s3-encrypted-ra.yaml
- templates/s3/sc-s3-synapse-ra.yaml
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-same-region-bucket-download/pull/24
> [IT-3812] Update cfn-cr-same-region-bucket-download lambda
