Sage-Bionetworks/service-catalog-library

ec2/sc-ec2-linux-ra.yaml

This creates two security groups. Which one gets used depends on whether the end user choose public or private subnet. I am making my best guess about what is needed by the majority of cases. Please review whether PublicSubnetSecurityGroup is too permissive.

Create inline security groups and conditionals to manage them

---

ec2/sc-ec2-windows-ra.yaml

apply similar networking decisions for linux product to windows product
Except, do not allow windows to be on public subnet -- don't think there's any use case for that

Edit windows product vpc, subnet, security group

---

ci/taskcat-params-verify-all.json
ec2/sc-portfolio-ec2.yaml
ec2/sc-portfolio-ec2VPC.yaml
ec2/sc-product-ec2-demowebserver.yaml
ec2/sc-product-ec2-linux.yaml
ec2/sc-product-ec2-webserver.yaml
ec2/sc-product-ec2-windows.yaml
ecs/sc-product-container-pipeline.yaml
ecs/sc-product-fargatecluster.yaml
ecs/sc-product-fargatetask.yaml
emr/sc-portfolio-emr.yaml
emr/sc-product-emr.yaml
emr/sc-product-emrsparkhbase.yaml
labs/end-to-end-it-lifecycle-management/cfn/lab.yaml
labs/end-to-end-it-lifecycle-management/cfn/lab_v2.yaml
rds/sc-portfolio-rds.yaml
rds/sc-product-rds-mariadb.yaml
rds/sc-product-rds-mssql.yaml
rds/sc-product-rds-mysql.yaml
rds/sc-product-rds-postgresql.yaml
s3/sc-portfolio-s3.yaml
s3/sc-product-s3-private-enc.yaml
s3/sc-product-s3-private-mfa.yaml
s3/sc-product-s3-private-trans.yaml
s3/sc-product-s3-private.yaml
s3/sc-product-s3-public.yaml
templates/taskcat-verify-all.yaml
vpc/sc-portfolio-vpc.yaml
vpc/sc-product-vpc.yaml

Setup templates so we can pass a product version string when deploying
templates to AWS.  The idea is to tag them in git and have the tag appear
as the product version in AWS service catalog.

Setup service catalog product versioning

---

s3/sc-s3-encrypted-ra.yaml

Modify simple S3 bucket template to accept multiple user ARNs so that multiple
people can access the bucket.

Allow multiple users access private bucket

---

ec2/sc-ec2-linux-ra.yaml

Add an option parameter to open a single port if the public network is selected

Add single open port param to linux ec2 instances

---

s3/sc-s3-encrypted-ra.yaml
s3/sc-s3-synapse-ra.yaml

Clears up confusing example which when followed causes template to fail when executed by SC

Fix default and constraint deescription for s3 buckets

---

s3/sc-s3-encrypted-ra.yaml

This adds back in the explicit Deny on trying to upload objects that are not encrypted. @zaro0508, please see if this whole policy makes sense to you.

Add Deny on unencrypted objects back to BucketPolicy in encrypted bucket

---

iam/sc-enduser-iam.yaml

This will prevent template from being viewable when a stack is examined.

Add managed policy to hide template to protect secrets

---

s3/sc-s3-synapse-ra.yaml

This resolves issue https://github.com/Sage-Bionetworks/scipoolprod-sc-lib-infra/issues/19
The owner.txt file is added using the CFN S3 objects macro.

add owner file to synapse bucket

---

ec2/sc-ec2-linux-jumpcloud.yaml

This adds init metadata to a ec2 instance template to set register the instance with Jumpcloud. 
- Parameter KeyPair is removed
- Parameter OwnerEmail is added
- No parameters were added for Jumpcloud. The SecureString parameters are pulled from SSM using awscli.
I have left several commented lines where I attempted to use Cloudformation Dynamic References. Unfortunately dynamic references cannot be used in the Parameters section nor in Init sections.
I was not able to fully test this template manually because even when assuming the Admin role I receive a message that I do not have permission to decrypt the strings.

Add Jumpcloud setup to ec2 template intended for use by ServiceCatalog

---

s3/sc-s3-synapse-ra.yaml

Using the API to upload the owner.txt file for a synapse bucket requires
setting the ACL public-read otherwise (the principla) synapse
still cannot read the file.

Set synapse owner.txt file ACL

---

ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-linux-ra.yaml
ec2/sc-ec2-windows-ra.yaml

The SC linux and windows provisioner templates provision EC2s from AWS published AMIs.
It's not good practice to depend on AMIs from AWS because AWS may deprecate and remove
those AMIs from us at any time. When that happens our templates will be in a broken
state. Instead we will provision instances from Sage AMIs.
This resolves issue #31

Use sage AMIs

---

s3/sc-s3-synapse-ra.yaml

The more appropriate ACL is authenticated-read[1] as suggested by
@wpoehlm in PR https://github.com/Sage-Bionetworks/synapseDocs/pull/544/commits/ef739561cd5ff99c67ef03e8e23f96305f1898ee
[1] https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html

update synapse bucket owner.txt file ACL

---

iam/sc-ec2vpc-launchrole.yaml

Add cloudformation:CreateChangeSet to the EC2 launch role. This is required for the lambda transform SsmParam to work in Service Catalog.

Add cloudformation:CreateChangeSet to ec2vpc launch role

---

ec2/sc-ec2-windows-jumpcloud.yaml

The primary purpose of this PR is creating a new Windows instance that includes cfn and jumpcloud scripts in the Init section and in UserData. That part is based on lessons learned from doing a similar task for the Linux Jumpcloud integration, as well as existing implementation in [aws-infra](https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/managed-ec2-win-v4.j2). The secondary purpose is to change the patch baseline to apply only security updates.

Create windows ec2 instance with jumpcloud integration

---

ec2/sc-ec2-linux-jumpcloud.yaml

Add init script for tagging the volume.
This is based on existing scripts in aws-infra, but had to be rewritten to pull the tags from the instance, since we're not setting the tag values as template parameters.
The script's been tested and works; the question is whether the instance will have been tagged at the time the init script runs.

Add volume tagging to sc-ec2-linux-jumpcloud

---

ec2/sc-ec2-windows-jumpcloud.yaml

- Remove too-permissive ssm policies from InstanceRole
- Remove all patching resources. Patching will be re-added when IT can come up with a strategy for this -- it is outside the scope of Service Catalog development.
These are the same changes as applied to the linux jumpcloud template yesterday.

Remove overly permissive SSM policies and patching resources

---

iam/sc-enduser-iam.yaml

SC fails to provision the S3 synapse bucket product. Seeing a few
AccessDenied errors in cloudtrail during provisioning of the bucket.
This is an attempt to allow access to those actions.
fixes https://sagebionetworks.jira.com/browse/SC-14

attempt to fix SC s3 synapse bucket product

---

s3/sc-s3-synapse-ra.yaml

Seeing the following error when provisioning an S3 synapse bucket:
"errorCode":"ValidationException","errorMessage":"Processed template of
Stack SC-237179673806-pp-pdfndguyqnu3k is not ready. Specify Original to
get user-submitted template
My hypothesis is that the SynapseOwnerFile resource is attempting to
create a file however the bucket has not been created yet.
We add a DependsOn to make the file dependent on the bucket.

Attempt to fix s3 synapse bucket provisioning

---

s3/sc-s3-synapse-ra.yaml

This reverts commit e50a34934949a355db892e4d37d70c4fb5aca352.
This change is not neccessary, PR #57 fixes the SC s3 synapse bucket

Revert "Attempt to fix s3 synapse bucket provisioning (#51)"

---

iam/sc-s3-launchrole.yaml

Our Synapse S3 bucket template contains a macro (lambda).  When provisioning
the template thru the SC it failed to execute the lambda because it didn't have
permissions.  It would fail with the following (not helpful) message:
Failed to execute transform 237179673806::S3Objects. Rollback requested by user.
Setting the permissions in the lambda itself does not work because the service
catalog role will override those permissions.  Fix this by giving the SC role
the full lambda permissions.

Fix S3 synapse bucket provisioning

---

s3/sc-s3-cidr-ra.yaml
s3/sc-s3-encrypted-ra.yaml
s3/sc-s3-mfa-ra.yaml
s3/sc-s3-public-ra.yaml
s3/sc-s3-synapse-ra.yaml
s3/sc-s3-transition-ra.yaml

SC end users don’t have list bucket permission so they can’t just goto the S3
console and type the bucket name to access their bucket.  However they can acess
the bucket with a direct link.  We provide a direct link in the outputs
to make it easier to navigate to the bucket from the provisioned
products list page.

add a bucket URL

---

iam/sc-enduser-iam.yaml

Add permission to allow SC end users to start/stop/reboot their
instances. Following instrcutions from the AWS docs[1]
[1] https://docs.aws.amazon.com/servicecatalog/latest/adminguide/using-service-actions.html

[SC-26] update SC end user permissions

---

ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

1. add new configset to create a file that can be sourced to add environment vars before several steps that need them
2. alter jc associate step to use env vars so that OwnerEmail parameter can be removed
3. add tag volume step
4. set keypair default 
@zaro0508 thinking keypair and windows ami-id should not be parameters here, even though I have defaults -- thoughts?

Add configsets for env vars and volume tagging

---

ec2/sc-ec2-linux-jumpcloud.yaml

- always use private security group
- if public network selected, additionally attach public security group

Always use private security group

---

ec2/sc-product-ec2-demowebserver.yaml
ec2/sc-product-ec2-linux-jumpcloud.yaml
ec2/sc-product-ec2-linux.yaml
ec2/sc-product-ec2-webserver.yaml
ec2/sc-product-ec2-windows-jumpcloud.yaml
ec2/sc-product-ec2-windows.yaml
ecs/sc-product-container-pipeline.yaml
ecs/sc-product-fargatecluster.yaml
ecs/sc-product-fargatetask.yaml
emr/sc-product-emr.yaml
emr/sc-product-emrsparkhbase.yaml
glue/sc-product-glue.yaml
labs/end-to-end-it-lifecycle-management/cfn/SC_ConnectorForServiceNowv2.0.2-AWS_Configurations.yaml
labs/end-to-end-it-lifecycle-management/cfn/lab.yaml
labs/end-to-end-it-lifecycle-management/cfn/lab_v2.yaml
rds/sc-product-rds-mariadb.yaml
rds/sc-product-rds-mssql.yaml
rds/sc-product-rds-mysql.yaml
rds/sc-product-rds-postgresql.yaml
s3/sc-product-s3-private-enc.yaml
s3/sc-product-s3-private-mfa.yaml
s3/sc-product-s3-private-trans.yaml
s3/sc-product-s3-private.yaml
s3/sc-product-s3-public.yaml
s3/sc-product-s3-synapse.yaml
serverless/sc-product-serverless-lambda.yaml
vpc/sc-product-vpc.yaml

Include the support snippet info from an external file.
This depends on PR https://github.com/Sage-Bionetworks/admincentral-infra/pull/77
Note from [AWS::Include docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/create-reusable-transform-function-snippets-and-add-to-your-template-with-aws-include-transform.html)
```
If your snippets change, your stack doesn't automatically pick up those changes.
To get those changes, you must update the stack with the updated snippets.
If you update your stack, make sure your included snippets haven't changed
without your knowledge. To verify before updating the stack, check the change set.
```

[SC-13] Include support info

---

ec2/sc-ec2-linux-jumpcloud.yaml

Allow SC users to open ports by selecting an application that will run
on the instance. The idea is to set ingress rules based on default ports
required by certain applications.  Deviating from the default application
ports would be a more custom setup which may require using the scicomp
provisioner

[SC-4] open application ports

---

s3/sc-portfolio-s3-basic-development.yaml
s3/sc-portfolio-s3-basic.yaml
s3/sc-product-s3-private-enc.yaml
s3/sc-product-s3-synapse.yaml
templates/taskcat-verify-all.yaml

This performs similar changes to S3 portfolios as made to the EC2 portfolios in https://github.com/Sage-Bionetworks/scipoolprod-sc-lib-infra/pull/78.

SC-16 Add StackDatetime and allow product-level version in S3 portfolio stack

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml

This adds a cfn-init script for tagging `Name` of a linux instance provisioned through Service Catalog, by looking up the name used for the provisioned product and using that for the tag value.
This PR depends upon https://github.com/Sage-Bionetworks/scipoolprod-infra/pull/67.

SC-29 tag linux instance with name used for provisioned product

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml

Since SC users are given a dashboard of info after provisioning
SC products, the "provisioned products" list, the idea in this PR
is to use that dashboard to provide additional additional info
to users.  In this specific case we are providing info on how
to connected to a provisioned instance.

[SC-27] Provide SC users with connection info

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml

This PR handles volumes differently depending on whether the distribution is Amazon Linux or Ubuntu. See [JIRA SC-47](https://sagebionetworks.jira.com/browse/SC-47).
The way @zaro0508 wrote SC-47, it sounds like the minimum `VolumeSize` should be different. However, there is no difference in minimum volume size between the two distros, only in `DeviceName`.

Use different directories for volume depending upon linux os chosen

---

ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml

* Add windows version of script for tagging name on instance
* Updated version of tag-instance-volume script
* Add `--no-progress` on choco installs -- progress lines fill up logs annoyingly
* Also, set up permament "development" product for windows jumpcloud. Will do same for linux.
This is based on the previous PR for tagging linux instances with names: https://github.com/Sage-Bionetworks/scipoolprod-sc-lib-infra/pull/82

Add instance name tag for windows

---

ec2/sc-ec2-linux-jumpcloud-development.yaml
ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
ec2/sc-ec2-windows-jumpcloud-development.yaml
ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml
ec2/sc-portfolio-ec2.yaml
ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml

Adds product and template for a Linux notebook product.
Currently the only choice for "Notebook Type" is Rstudio. Eventually we'll add Jupyter as an option too.
Note, this is the production version. There is a separate PR for the development version: https://github.com/Sage-Bionetworks/scipoolprod-sc-lib-infra/pull/90

Add production notebook product

---

dev-deploy-templates.sh
ec2/sc-ec2-linux-jumpcloud-notebook-development.yaml
ec2/sc-portfolio-ec2-development.yaml
ec2/sc-product-ec2-linux-jumpcloud-notebook-development.yaml

Adds product and template for a Linux notebook product.
Currently the only choice for "Notebook Type" is Rstudio. Eventually we'll add Jupyter as an option too.
Note, this is only the development version, I'll have to create a PR for the actual product too.

Add development notebook product

---

dev-deploy-templates.sh
ec2/development/sc-ec2-linux-jumpcloud-development-tthyer.yaml
ec2/development/sc-portfolio-ec2-development-tthyer.yaml
ec2/development/sc-product-ec2-linux-jumpcloud-development-tthyer.yaml
ec2/sc-ec2-linux-jumpcloud-development.yaml
ec2/sc-ec2-linux-jumpcloud-notebook-development.yaml
ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-workflows-development.yaml
ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml

1. Create a development folder for dev resources just to make the ec2 folder easier to manage
2. Used aws:servicecatalog:provisioningPrincipalArn to extract the owner's email. This is set into the environment variables and used in the script to register with Jumpcloud, the script to tag the root volume. Finally, I also apply OwnerEmail as a tag back to the instance.
follow up work:
1. do same for windows
2. move other development resources into development folder to tidy up ec2 dir

Sc-83 change owner email source

---

ec2/development/sc-ec2-linux-jumpcloud-development.yaml
ec2/development/tthyer/sc-ec2-linux-jumpcloud-development-tthyer.yaml
ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml

Switch linux-jumpcloud product to use the packer-base-amazonlinux2 v1.0.1

Use packer-base-amazonlinux2 v1.0.1 

---

ec2/development/sc-ec2-linux-jumpcloud-development.yaml
ec2/development/sc-ec2-linux-jumpcloud-notebook-development.yaml
ec2/development/sc-ec2-linux-jumpcloud-workflows-development.yaml
ec2/development/sc-ec2-windows-jumpcloud-development.yaml
ec2/development/tthyer/sc-ec2-linux-jumpcloud-development-tthyer.yaml
ec2/development/tthyer/sc-portfolio-ec2-development-tthyer.yaml
ec2/development/tthyer/sc-product-ec2-linux-jumpcloud-development-tthyer.yaml
ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml

Parameterize the vpc name to make templates more generic
so it can be re-used to deploy to multiple AWS accounts.
The purpose is to allow us to easily create the same SC in
another account for development.

[SC-111] Make templates reusable

---

ec2/sc-ec2-actions.yaml

This template can be used to create SC actions in an AWS account.
It depends on having the cfn-sc-actions-provider installed
PR https://github.com/Sage-Bionetworks/scipoolprod-infra/pull/91
installs the cfn-sc-actions-provider

[SC-26] template to create SC actions

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
iam/sc-enduser-iam.yaml

Passes pre-commit
This allows users to startsession on instances associated with their Synapse userid and adds the SSM core policy to a Linux instance profile. We can use this for other instance types, potentially.
Depends: 
- Adding tags for filtering startsession requests: https://github.com/Sage-Bionetworks/service-catalog-utils/pull/3

Add StartSession policy for remote access

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
iam/sc-enduser-iam.yaml

This is a change to the ServiceCatalogEnduser role that allows an assumed role to call StartSession through the SSM service on instances tagged with the roleid and their unique sessionname. This PR is revised to correct an error in parsing allowed by this CFN version. I tested it in scipoolprod.

SC-54 add start-session filter

---

iam/sc-enduser-iam.yaml

Removes parameter from enduser template that was causing complexity elsewhere. Should no longer be needed since we are splitting dev from prod account.

Remove RoleAndGroupName parameter from sc-enduser-iam

---

dev-deploy-templates.sh

Temporary fix to get development process working again: fix url name in dev deploy script.

Fix library name in url in dev-deploy-templates.sh

---

s3/sc-portfolio-s3-basic.yaml

We export the portfolio ID so we can import into a downstream
template.

[SC-128] export the portfolio id

---

ec2/sc-portfolio-ec2.yaml

Refactor to use cross stack imports intead of passing in parameters.
We also removed unnessary paramters and make it more conducive for
sceptre deployment.
The main idea here is to make the template easier to understand for
preparation to remove 'AWS::CloudFormation::Stack' from this template

[SC-111] Refactor portfolio template

---

iam/sc-enduser-iam.yaml

It turns out we need to specify the region explicitly in order to match permissions between the principal and resource, which makes sense because otherwise it would be inadvertently excessive.

Specify AWS Region

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml

This enabled adding the AllowedAccessCaller tags at launch time. I've added a v1.0.1 release: https://github.com/Sage-Bionetworks/service-catalog-utils/releases/tag/v1.0.1

Reference v1.0.1 of service-catalog-utils in std linux ec2

---

s3/sc-portfolio-s3-basic.yaml

Refactor to use cross stack imports intead of passing in parameters.
We also removed unnessary paramters and make it more conducive for
sceptre deployment.
The main idea here is to make the template easier to understand for
preparation to remove 'AWS::CloudFormation::Stack' from this template

[SC-111] Refactor S3 portfolio template

---

s3/sc-portfolio-s3-basic.yaml
s3/sc-product-s3-private-enc.yaml
s3/sc-product-s3-synapse.yaml

Nested stacks make things confusing and makes cloudformation
very difficult to test. We remove S3 nested stack and will deploy
stacks with sceptre. Scepter will manage the dependencies between
stacks.

[SC-111] refactor to remove nested S3 stacks

---

ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-product-ec2-linux-jumpcloud.yaml
ec2/sc-product-ec2-windows-jumpcloud.yaml
s3/sc-product-s3-private-enc.yaml
s3/sc-product-s3-synapse.yaml

For SC-134 we need to make product names configurable, too. Otherwise, when testing the multiples of the same product appear in the list of possible products to provision for the user who is testing.

Make product names configurable

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml

This change allows an instance to read the roleid of a rolename in order to write a tag to itself. This permission set should be limited to Service Catalog instances that need to limit access to OIDC sessionNames. Thank you, @tthyer for raising the issue of instance profiles.

Allow reading role information in Linux instance profile

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml

Reverts Sage-Bionetworks/service-catalog-library#146
This resulted in an error with provisioning a Linux EC2 with Jumpcloud product, with the error message that `/Resources/ReadAssumedRoleInformationPolicy/Type/PolicyDocument] 'null' values are not allowed in templates`

Revert "Allow reading role information in Linux instance profile"

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml

In scipool-infra, I changed the name of a stack that gets imported by instances in this library, so this corrects the stack name.

Sync with rename of imported stacks

---

s3/sc-s3-encrypted-ra-v1.0.0.yaml
s3/sc-s3-synapse-ra-v1.0.0.yaml

Add bucket policy custom resource to s3 templates.
This custom resource will create a policy that adds the provisioning user as a principal, allows extra principals to be added, and optionally requires encryption.
This PR depends on https://github.com/Sage-Bionetworks/scipool-infra/pull/115
For more information about the custom resource, see https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-bucket-policy/pull/1

Use bucket policy custom resource in s3 bucket templates

---

s3/sc-s3-encrypted-ra-v1.0.0.yaml

The RequireEncryption property is no longer necessary for the policy custom resource.

Remove the RequireEncryption property from SCS3BucketPolicy

---

ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml

Created `SynapseEmail` attribute in jumpcloud and make instance
initilization use that value instead of the jumpcloud `email` value
to associate JC instances to users.
The SynapseEmail attribute would have a value like "jsmith@synapse.org"
I believe this also fixes issue SC-145
The windows fix depends on PR https://github.com/Sage-Bionetworks/infra-utils/pull/45
and will require a new infra-utils tag

[SC-137] Fix jumpcloud integration

---

ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml

Linux templates need to use a new utils release so the tag path of the AccessApprovedCaller is correct.

Up to new utils release

---

ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml

Provisioning windows throws the following error:
"API: ec2:RunInstances Not authorized for images: [ami-074545a6fb2313e2c]"
Apparently Windows AMI are deprecated when a new version is released:
https://stackoverflow.com/a/22665386/1094247
To fix we need to update to the latest supported AWS windows AMI
The real fix is to create own windows AMI using packer.

Fix windows deployments

---

ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml

t3.nano and t3.micro can be used just to run services but would
be way too under powered for RDP sessions.  t3.small is probably
the minimal required for RDP. Update to match most common use case

update windows instance type

---

ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-product-ec2-linux-jumpcloud.yaml
ec2/sc-product-ec2-windows-jumpcloud.yaml
s3/sc-product-s3-private-enc.yaml
s3/sc-product-s3-synapse.yaml

This replaces the hack using StackDatetime with the new property ReplaceProvisioningArtifacts for forcing update of the `LoadTemplateFromUrl` template content in product versions.
This PR is dependent upon https://github.com/Sage-Bionetworks/scipool-infra/pull/124.

Use ReplaceProvisioningArtifacts in product templates to allow product version template updates

---

ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml

Use the new service-catalog-utils file to fix jumpcloud integration with
provisioned instances
* Switch ordering of SetupJumpcloud and SetTags.  Tagging volume and
instance should run before setting up jumpcloud integration
* run new python script to associate EC2 instances to a JC user
This PR depends on PR https://github.com/Sage-Bionetworks/service-catalog-utils/pull/6
and will require a new tag of service-catalog-utils

[SC-145] Fix jumpcloud integration

---

ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml

Old workflow AMI was created as a private AMI which caused the
following failure when deployed with the SC:
API: ec2:RunInstances Not authorized for images: [ami-01866cea595e4f968]
The newer AMI built as a public AMI so it should fix this issue.

[SC-156] update to latest workflow AMI

---

ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-product-ec2-linux-jumpcloud.yaml
ec2/sc-product-ec2-windows-jumpcloud.yaml
s3/sc-product-s3-private-enc.yaml
s3/sc-product-s3-synapse.yaml

We need to make an update to one of the fields of the version to actually trigger an update, as it appears that simply changing the template content does not do this. Adding StackDatetime back into description for that purpose. 
After this is merged I will revert https://github.com/Sage-Bionetworks/scipool-infra/pull/124.

Re-add StackDatetime to trigger version update in products

---

ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml

This fixes commit 98cf785349.  That commit reference a packer-rstudio
AMI instead of a packer-workflow AMI.  This fixes it so that it's
now referencing the latest ver of the packer-workflow AMI

Fix AMI reference

---

ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml

Apparently the notebook and workflow instances don't know the
source command so @tthyer suggest replacing it with the period.
Error during instance initilization:
[ERROR] Command 02_associate_jc_systems (source /opt/sage/bin/instance_env_vars.sh && /usr/bin/python3 /opt/sage/bin/associate_jc_systems.py) failed
[DEBUG] Command 02_associate_jc_systems output: /bin/sh: 1: source: not found

Replace source command with '.'

---

ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml

Apparently '.' is more portable than source so changing it out
similar to commit eb06a0641

Replace source with '.'

---

ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml

We recently change the packer-workflows AMI to default to
16GB so set the default in the CFN template to match.
AMI change was in PR https://github.com/Sage-Bionetworks-IT/packer-workflows/pull/8

Increase default volume size

---

common/sc-tag-options.j2

The OwnerEmail tag is automatically applied by the provisioner now
so we no longer a tag option for it.

[SC-123] remove OwnerEmail tag option

---

ec2/sc-portfolio-ec2.yaml
ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-product-ec2-linux-jumpcloud.yaml
ec2/sc-product-ec2-windows-jumpcloud.yaml
s3/sc-portfolio-s3-basic.yaml
s3/sc-product-s3-private-enc.yaml
s3/sc-product-s3-synapse.yaml
s3/sc-s3-encrypted-ra-v1.0.0.yaml

PR https://github.com/Sage-Bionetworks/admincentral-infra/pull/84
created a new snippet (products.yaml).  The new snippet adds
owner and Distributor properties.  Now we can use the products
snippet for all Sage products.

Replace support with products snippet

---

ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml
ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.0.yaml
ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml

Instead of creating a new PrivateSubnetSecurityGroups for every EC2 instance
use VpnSecurityGroup export from internalpoolvpc.

[SC-30] Re-use VpnSecurityGroup

---

ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-product-ec2-linux-jumpcloud.yaml
ec2/sc-product-ec2-windows-jumpcloud.yaml
s3/sc-product-s3-private-enc.yaml
s3/sc-product-s3-synapse.yaml

Changed product names to something more standardized, removing "Jumpcloud" from all names.

Standardize default product names

---

ec2/sc-portfolio-ec2.yaml
iam/sc-enduser-iam.yaml
s3/sc-portfolio-s3-basic.yaml

The SCEnduserGroup was initially setup for IAM users to access the SC.
Now that we have users loging in thru synapse and assuming the
SCEnduserRole we no longer need SCEnduserGroup.
Note: deploying this PR requires that we first remove the `LinkEndusersGroup`
from the S3 and EC2 portfolios.

[SC-39] Remove SCEnduserGroup

---

ec2/sc-ec2-linux-jumpcloud-notebook-v1.0.2.yaml
ec2/sc-ec2-linux-jumpcloud-v1.0.2.yaml
ec2/sc-ec2-linux-jumpcloud-workflows-v1.0.2.yaml
ec2/sc-ec2-windows-jumpcloud-v1.0.0.yaml
ec2/sc-product-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-product-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-product-ec2-linux-jumpcloud.yaml

This PR depends on PR https://github.com/Sage-Bionetworks/service-catalog-utils/pull/8
* Update linux templates to support multiple portfolios.
The passed in AccessApprovedRoleId value is no longer used, the
refactored util scripts will lookup the AccessApprovedRoleId depending
on the role that the synapse user assumes.
* Remove AccessApprovedRoleId from windows template because it's not used at all
and we don't offer a ConnectionURI for windows.

[SC-65] support multiple portfolios

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml

This PR adds a security group to the notebook instance type that allowing ingress from the ALB in the appropriate Service Catalog account. 
The notebook template now includes a reference to a boot script in the service-catalog-utils repo that will substitute a variable into a path in the apache proxy config file. This script will only be needed for instances that run internal web servers and have the apache proxy, and so isn't needed for other instance types.
depends on https://github.com/Sage-Bionetworks/service-catalog-utils/pull/10  https://github.com/Sage-Bionetworks/service-catalog-library/pull/213 https://github.com/Sage-Bionetworks/scipool-infra/pull/143 https://github.com/Sage-Bionetworks/service-catalog-utils/pull/11

Add import security group for alb ingress and new boot script

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml

These are the changes to the notebook template required to make ALB routing work.
Depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-alb-rule/pull/1 https://github.com/Sage-Bionetworks/synapse-login-scipool/pull/40

Add target group, alb listener rule-making custom resource, and new NotebookConnectionUri

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml

The wrong name was used for the configSet that updates the apache proxy file in the UserData block.

Correct apache config set name in UserData

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

This change adds a Cloudformation signal counter to common instance templates so that the 'complete' status is reflected in the provisioned product only when all commands in the instance metadata bootstrapping complete successfully. 
This solution works with all current product types.

Add cfn signals to EC2 products

---

ec2/sc-ec2-windows-jumpcloud.yaml

AWS rotated their AMIs regularly and they seem to have
just changed them out so we need to update as well.

[SC-225] Update AWS Windows AMI

---

ec2/sc-ec2-linux-jumpcloud-workflows.yaml

Previously, we were adding the jumpcloud user to the docker group on the workflows instances. However, we removed all the jumpcloud bits but forgot to change this. The ubuntu user is already added to the docker group in the packer playbook; here, just adding the ssm-user as well, since that's the default user when logging in through the SSM shell.

[SC-226] Add ssm-user to docker group instead of jc user which no longer exists

---

ec2/sc-ec2-linux-jumpcloud-workflows.yaml

This isn't what I would ideally like, but it works. 
- creates ssm-user
- adds to docker group
- adds ssm-user as sudoer
I've tested this a bit in scipooldev and it appears to work -- I can connect through the ssm browser session as the ssm-user, can sudo without being prompted for a password, and ssm-user is a member of docker.
I would prefer to be able to configure things about the ssm-user that the ssm agent will create on login, but could find no way to do that.
I am creating the user and setting it up directly in UserData because when I attempt to set it up through a cfn-init config set command, the command appears to succeed, but the user doesn't exist after the command, like something that happens in a subshell.
Reminder, I will be out on Monday -- if we want to fix the bug faster, …

Add the ssm-user so that it can be added to the docker group

---

s3/sc-s3-synapse-ra.yaml

With the fix to PLFM-6358 we can now refactor to allow users to
provision Synapse bucket with multiple owners.

[SC-140] multiple synapse bucket owners

---

s3/sc-s3-encrypted-ra.yaml
s3/sc-s3-synapse-ra.yaml

The single purpose cfn-cr-bucket-tagger[1] custom resources is
deprecated[2]. It is being replaced with the multi purpose
cfn-cr-synapse-tagger[3 lambda
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-bucket-tagger
[2] https://github.com/Sage-Bionetworks-IT/cfn-cr-bucket-tagger/pull/6
[3] https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger
depends on Sage-Bionetworks/scipool-infra#185

re-route S3BucketTagger to SynapseTagger

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

Use the cfn-cr-synapse-tagger[1] custom resource to apply synapse
metadata[2] to EC2 instances as tags.
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger
[2] https://docs.synapse.org/rest/org/sagebionetworks/repo/model/UserProfile.html
depends on Sage-Bionetworks-IT/cfn-cr-synapse-tagger#9 Sage-Bionetworks/scipool-infra#185

[SC-190] use SynapseTagger to apply synapse tags to EC2s

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

This change removes the VpcName input parameter users see when
provisioning EC2s in the service catalog. We automatically set the
VPC specific parameters based on which account the EC2 is provisioned
in.

[SC-133] Remove VpcName input

---

ec2/sc-ec2-windows-jumpcloud.yaml

Provision instances with the new custom built Sage Windows AMI[1]
[1] https://github.com/Sage-Bionetworks-IT/packer-base-winserver2019
depends on Sage-Bionetworks-IT/packer-base-winserver2019#1

[SC-151] Use new Windows AMI

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

The functionality to apply product name tag and access role approved tag
has beeen moved to the Synapse tagger.  Renoving it from here.
depends on Sage-Bionetworks-IT/cfn-cr-synapse-tagger#13

[SC-168] Remove apply_name_tag.sh script

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

The functionality to apply tags to EC2 attached volumes has been moved
to the Synapse tagger. Renoving it from here.
depends on Sage-Bionetworks-IT/cfn-cr-synapse-tagger#14

[SC-168] Remove tag root volume script

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

Tagging instance is done with the synapse tagger so we no longer need
the bash scripts for tagging.

[SC-168] Remove tag instance script

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

The set_env_vars script and related policies are used to facilitate tagging
resources from an EC2 instance.  Now that we have moved to using the
cfn-cr-synapse-tagger[1] to do all the tagging work we can remove that script
and all it's associated policies.  This will make the template simpler
and make provisioning instances faster.
[1] https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger
depends on Sage-Bionetworks/service-catalog-utils#16

[SC-241] Fix EC2 tagging policy

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-linux-jumpcloud-workflows.yaml
ec2/sc-ec2-linux-jumpcloud.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

This reverts commit c2e6fe0085bf8423999fab87966b69a1c684ab2a.
This change breaks the EC2 notebook and windows products because those
products have dependencies on the script that sets env vars.
On windows the associate-jc-system.ps1 script assumes the SYNAPSE_USER_ID
environment variable has been set.
On notebook the packer-rstudio AMI's access.py script assumes a
Protected/AccessApprovedCaller tag to exist on the instance.

Revert "[SC-241] Fix EC2 tagging policy (#236)"

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml

was using an out of date reference that we didn't delete in the dev stack.
So the full integration was working in dev, but not in prod.

update reference to WriteToSSMPolicy (SC-260)

---

ec2/sc-ec2-linux-docker.yaml

A template for the service catalog to provision a linux EC2 with
docker.  Docker is installed into the packer-amazonlinux-docker AMI[1].
This template sets up policies to allow authorized users to access the
instance using the AWS Systems Manager (AWS SSM). 
[1] https://github.com/Sage-Bionetworks-IT/packer-amazonlinux-docker/tree/v1.0.0

[SC-251] ec2 linux docker product

---

ec2/sc-ec2-linux-docker.yaml
ec2/sc-ec2-linux-jumpcloud-workflows.yaml

Depending on the dataset size, 2 TB is limiting given the number of large intermediate files that get generated. I propose increasing the limit to 5 TB (just for the workflows product) to give more breathing room. I need this in case NF Tower isn't set up in time to meet deadlines for processing data in the imCORE project. 
I believe once this PR is merged, a new version of this repository will need to be minted and this [file](https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/sceptre/scipool/config/prod/sc-product-ec2-linux-jumpcloud-workflows.yaml#L18) will need to be changed.

Increase disk size limit for SC workflows product

---

s3/sc-s3-synapse-ra.yaml

restrict Put-Object calls to include bucket-owner-full-control
users using the AWS CLI must upload with `--acl bucket-owner-full-control`
to cause the ownership to change
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-bucket-policy/pull/4

[SC-312] switches ownership of uploaded objects to be that of the bucket

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml

Updating R-Studio product (v 2.1.2 of packer-rstudio) to use new AMI.   As per [SC-318](https://sagebionetworks.jira.com/browse/SC-318), this changes `/etc/security/limits.conf` to allow more concurrent open files.

SC-318 updating R-Studio product to use new AMI

---

s3/sc-s3-encrypted-ra.yaml
s3/sc-s3-synapse-ra.yaml

A bucket delete may fail due to having existing data in the bucket.
When a failure occurs the bucket will remain and SC will report that
the product is in a `Tainted` state.  When this occurs users cannot update
or terminate the product again which means they are stuck requiring
an AWS admin to help resolve the situation.
This change will make cloudformation ignore deleting the bucket.
When a user terminates the SC product the policy on the bucket
and the SC product is removed however the bucket itself is retained.
CFN doesn't even try to remove the bucket so it won't ever get into
the `tainted` state.  The bucket stays around and the policy is
removed so nobody has access to the bucket after an SC termination.
The effect is that the SC user thinks that the bucket has been deleted
however …

[SC-326] Retain bucket on SC product termination

---

s3/sc-s3-encrypted-ra.yaml
s3/sc-s3-synapse-ra.yaml

We SC users provision buckets they use it for a variety of different
things.  We don't really know their usage patters ahead of time.  They
can upload files and leave them around for a long time which can be
expensive.  Enabling intelligent tiering on their buckets may help us
reduce S3 storage costs.  Well, this is what @marcomarasca says anyways.

[SC-363]  Enable S3 intelligent tierring on buckets

---

batch/sc-batch-fargate.yaml

Add a SC product to run cron jobs on a schedule.  The cron jobs
will be run as AWS batch jobs.  Users can set the job to run on
a schedule or they can manually trigger the job with the submit
job API.
depends on https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/317 https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/320

[SC-306] Scheduled Jobs product

---

batch/sc-batch-fargate.yaml

The only workaround that I could find for allowing empty Secret and EnvVar parameters
is to not allow it at all.  Instead we set default values and user either needs to
accept the default values or replace them with their own VARS.  Setting the parameters
to an empty string will cause the deployment to fail.

[SC-306] Workaround for empty parameters

---

batch/sc-batch-fargate.yaml

Some parameters cannot be left blank otherwise provisioning will fail.  We use
regular expression to make cloudformation enforce required parameters.

[SC-306] Make parameters required

---

batch/sc-batch-fargate.yaml

* Remove AllowedPattern from EnvVars because that's a CommaDelimitedList
parameter which does not support AllowedPattern
* AllowedPattern requires a default value to validate the parameter
therefore we need to add a default to the Command parmeter
* Use regex from example https://www.examplefiles.net/cs/122000

[SC-306] fix required parameters

---

batch/sc-batch-fargate.yaml

* A dockerfile may run the require commands so user may not
need to pass in a command to run.  This makes the command an
optional input parameter.
* Change the separater to space instead of pipe to match how the user
passes in the command using the docker CLI,
https://docs.docker.com/engine/reference/builder/#cmd

[SC-373] Make Command parameter optional

---

batch/sc-batch-fargate.yaml

The scheuled jobs product failed to deploy because the ContainerProperties
Command expects a list of strings.
```
Property validation failure: [Value of property {/ContainerProperties/Command} does not match type {Array}]
```
To fix that we need to use the CFN split function to create a list from
a space delimited string of commands.

[SC-306] Fix Command parameter

---

batch/sc-batch-fargate.yaml

Setup a lambda to tag each batch resource for the scheduled jobs
product. The lambda gets triggered when a user provisions the
scheduled jobs product in the service catalog
depends on https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger/pull/30

[SC-379] update scheduled jobs product with tagging

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml

SC-383: Updating the version of R and R Studio used in the RStudio Notebook product.  This updates the Notebook to use the new AMI built with Packer.

SC-383: Updating AMI for RStudio Notebook

---

ec2/sc-ec2-linux-docker.yaml
ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

We use the transit gateway to route traffic between the hub
and spoke VPCs. To allow access to resources in a spoke VPC we need
to give the hub VPC access to the resources. This adds an SG ingress
to resources provisioned in our spoke VPCs which will allow VPN users
access to the resources in the spoke VPCs.

[IT-1234] AWS Security group for TGW

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml

This reverts commit b6cde24904f9bc949c38c380863ad8211c66a84b.
The packer-rstudio v2.1.6 is broken. Reverting back to last
known good AMI

Revert "SC-383: Updating AMI for RStudio Notebook"

---

ec2/sc-ec2-linux-docker.yaml

Update the service catalog docker template to use the
lastest amazon linux 2 base AMI.

[SC-390] Update docker product AMI

---

s3/sc-s3-synapse-ra.yaml

Disable ACLs to simplify access management of data
in S3 buckets.  This is a recommendation by AWS
https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/

[IT-2075] Disable S3 bucket ACLs

---

s3/sc-s3-synapse-ra.yaml

This is a fix to PR #280 (setting `ObjectOwnership: BucketOwnerEnforced`)
When we do that we also need to remove the ACL setting from the S3Object
macro otherwise we'll get the following error..
```
[ERROR] ClientError: An error occurred (AccessControlListNotSupported) when calling
the PutObject operation: The bucket does not allow ACLs
Traceback (most recent call last):
File "/var/task/resource.py", line 72, in handler
s3_client.put_object(**target)
File "/var/runtime/botocore/client.py", line 391, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 719, in _make_api_call
raise error_class(parsed_response, operation_name)
[ERROR] ClientError: An error occurred (AccessControlListNotSupported) when calling the
PutObject operation: …
```

[IT-2075] remove bucket ACL setting

---

ec2/sc-ec2-linux-docker.yaml
ec2/sc-ec2-linux-jumpcloud-notebook.yaml
ec2/sc-ec2-windows-jumpcloud.yaml

Propagate the Service Catalog tags from the EC2 instance to its associated EBS volumes.

[IT-2132] Propagate tags from instance to volumes

---

batch/sc-batch-fargate.yaml

Add options to service catalog scheduled job product to allow users to set the job timeout and retries.

[IT-2731] Allow user to set job timeout and retries

---

ec2/sc-ec2-linux-jumpcloud-notebook.yaml

New AMI contains newer distro and apps versions:
* Ubuntu 22.04 (jammy jellyfish)
* python 3.10.6
* rstudio server 2023.03.1+446 (Cherry Blossom) for Ubuntu Jammy
* apache 2.4.52
depends on https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-jammy/pull/1  https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/65

[SC-383] Update EC2 notebook with new AMI

---

templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml

Update packer-rstudio AMI image
depends on https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/69

Update AMI for rstudio notebook product

---

templates/batch/sc-batch-fargate.yaml

There’s some conflicting information regarding fargate in AWS docs. The doc for batch[1] says `18432` is a valid option, while the doc for ECS[2] and the doc for cloudformation[3] says it is not a valid value.
All docs indicate that `8192` and `16384` are valid so it's probably a safe bet.
[1] https://docs.aws.amazon.com/batch/latest/APIReference/API_ResourceRequirement.html
[2] https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
[3] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-memory

[IT-3019] Fix fargate memory size

---

templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml

This PR updates the notebook product to Ubuntu2022/R4.1/RStudio202203. This is an attempt to move forward in upgrading the product.
Depends on https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/74

SC-383: Update OS/R4.1/RStudio202203

---

templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml

This PR updates the AMI ID to the latest build.
Depends on https://github.com/Sage-Bionetworks-IT/packer-rstudio/pull/75.

SC-383: Update amiId

---

templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml

This PR updates the service-catalog-utility scripts to pick up https://github.com/Sage-Bionetworks/service-catalog-utils/pull/23 .

SC-383: Bump version to take bugfix

---

.pre-commit-config.yaml
templates/s3/sc-s3-encrypted-ra.yaml

update of pre-commit linters resulted in this warning..
```
W3045 Consider using AWS::S3::BucketPolicy instead of AccessControl
templates/s3/sc-s3-encrypted-ra.yaml:40:7
```
Remove AccessControl setting because it is now disabled by default and bucket owner enforced is enabled by default.  This is what AWS recommends[1]
[1] https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html#requiring-bucket-owner-enforced

Update pre-commit linters

---

templates/ec2/sc-ec2-linux-docker.yaml
templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml
templates/ec2/sc-ec2-windows-jumpcloud.yaml

We have decided that the best option to balance performance, compability and cost would be to only allow the use of AMD instances[1] in the service catalog.  This change restricts the list of instances users get to select when provisioning service catalog EC2 instances.  It also attempts to reduce the number of instance types that we support by removing redundant types.
[1] https://aws.amazon.com/ec2/instance-types/
depends on #312

[IT-3222] Only allow AMD instances

---

templates/ec2/sc-ec2-linux-docker.yaml

Update the AmazonLinuxDocker base image to one that has a more recent version of Python installed.

[SC-409] Update packer-amazonlinux-docker AMI ID

---

templates/ec2/sc-ec2-linux-docker.yaml

Test the latest AMI build, which now includes cfn-init and cfn-signal. Also increase minimum volume size to match the minimum size from the template.

[SC-409] Test updated base AMI

---

templates/ec2/sc-ec2-linux-docker.yaml
templates/ec2/sc-ec2-linux-jumpcloud-notebook.yaml

We are seeing errors that the instance types are not available in us-east-1a. From the CLI (ec2.describe-instance-type-offerings), the older ones would be...

IT-3118: Replace *7a by *6a since not available

---

templates/ec2/sc-ec2-linux-docker-notebook.yaml

Swapping generic RStudio container for a version maintained by Sage
Depends on https://github.com/Sage-Bionetworks-IT/rstudio-service-catalog/pull/1
After the upstream PR is merged we also have to tag `Sage-Bionetworks-IT/rstudio-service-catalog` with v1.0.0.

IT-3317: Swapping generic RStudio container for a version maintained by Sage

---

templates/ec2/sc-ec2-linux-docker-notebook.yaml

The previous version had two mistakes in mounting a folder from the parent EC2 into the notebook container:
- The working directory for Jupyter is `/home/jovyan/work` not `/home/jovyan/workdir`.
- In RStudio we mounted the (empty) EC2 folder to `/home/rstudio` which overwrote all the packages, venv, etc. that were intalled in the user homedir. This update simply mounts the host folder into the (otherwise non-existent) `/home/rstudio/work`.
Just for consistency we rename the host folder from `/home/ssm-user/workdir` to `/home/ssm-user/work`.
Depends on https://github.com/Sage-Bionetworks-IT/rstudio-service-catalog/pull/2, which will also have to be tagged with `v1.0.1` for this PR to work.

IT-3317: Correct volume mounts; update RStudio container to v1.0.1

---

templates/ec2/sc-ec2-windows-jumpcloud.yaml

* chocolately failed to install because the latest version depends on .NET framework 4.8 and requires a reboot after install.  As a quick workaround we are going to pin to an older version of chocolately
* The Jumpcloud agent existing script is outdated because it contains a download url location that is no longer valid. To fix we are updating to use a newer version of the agent install script which is provided by Jumpcloud support[1]
[1] https://github.com/TheJumpCloud/support/tree/master

[IT-3425] Fix chocolately and JC agent installs

---

templates/ec2/sc-ec2-windows-jumpcloud.yaml

IMDSv1 can be disabled by the AMI, upgrade to IMDSv2 everywhere.

[IT-3369] Upgrade set_env_vars_file.ps1 to use IMDSv2

---

templates/ec2/sc-ec2-windows-jumpcloud-test.yaml

Test upgrading from Windows Server 2019 to Windows Server 2022 by creating a new template. This new template will be used to create a new SC product in sc-dev.sageit.org. Once the new product has been validated, these template changes can be ported over to the current SC product, and the test template removed.

[IT-3456] Test Windows OS upgrade

---

templates/ec2/sc-ec2-linux-docker-notebook.yaml
templates/ec2/sc-ec2-linux-docker.yaml

The nano instance type is not adequate for our service catalog instances so lets remove them.  Users still have lots of options to use other instances types.

[IT-3420] remove nano instance type

---

templates/ec2/sc-ec2-linux-docker.yaml

A new amazonlinux image was built in April, but this template was not updated. Use the latest version of the image.

[IT-3547] Use latest amazonlinux version

---

templates/ec2/sc-ec2-linux-docker-notebook.yaml

IT-3421:  
Refer to notebook container and reverse proxy by Major.minor tag (1.0) instead of Major.minor.patch tag (1.0.1); This will applying security updates to containers by pushing a new 'patch' version.
Run Watchtower on notebook EC2.  This will perform a daily check for a new version of each container with the given Major.minor patch and replace the existing container with the new one.  (Note that `IT` should be judicious in pushing patches and should notify users in advance of the interruption.)

IT-3421:  Refer to containers by Major.minor tags; run Watchtower

---

templates/s3/sc-s3-encrypted-ra.yaml
templates/s3/sc-s3-synapse-ra.yaml

Security hub says we should enable per bucket access flags when creating buckets to make sure they are private.

[IT-4074] Enable access flags for S3 buckets

---

templates/ec2/sc-ec2-linux-docker-notebook.yaml

update notebook product from rstudio-service-catalog:1.1 to 1.2
Depends on Sage-Bionetworks-IT/rstudio-service-catalog#14
and then tagging with version 1.2.0

SYNR-1544: update notebook product from rstudio-service-catalog:1.1 to 1.2
